#!/usr/bin/env bash
set -eo pipefail

# create-worktree.sh — Create a git worktree with auto-configured ports
#
# Usage:
#   create-worktree.sh <project> <branch> [slot]
#
# Examples:
#   create-worktree.sh bloasis feature/new-api        # auto-assigns slot
#   create-worktree.sh BSNexus fix/redis-bug 2        # explicit slot 2
#
# Port formula: base_port + 10000 + (slot - 1)
#   bloasis slot 1: APP=18000, FRONTEND=13000, PG=15432, REDIS=16379
#   bloasis slot 2: APP=18001, FRONTEND=13001, PG=15433, REDIS=16380

WORKS_DIR=~/Works
OFFSET=10000
MAX_SLOTS=5

# ─── Project port definitions ────────────────────────────────────────
# Format: PROJECT APP FRONTEND PG REDIS [EXTRA_NAME=EXTRA_PORT ...]
# Use - for unused ports
get_base_ports() {
  case "$1" in
    bloasis)        echo "8000 3000 5432 6379" ;;
    BSGateway)      echo "4000 3300 5433 6380" ;;
    BSNexus)        echo "8100 3100 5434 6381" ;;
    bsai)           echo "8200 3200 5435 6382 KEYCLOAK=8080" ;;
    BSForge)        echo "8300 - 5436 6383" ;;
    BSage)          echo "8400 3400 - -" ;;
    MetaSummarizer) echo "- - - -" ;;
    BSupervisor)    echo "8500 3500 5437 6384" ;;
    BSVibe-Auth)    echo "- 5179 5438 6385" ;;
    bsvibe-python)  echo "- - - -" ;;
    *)              return 1 ;;
  esac
}

ALL_PROJECTS="bloasis BSGateway BSNexus bsai BSForge BSage MetaSummarizer BSupervisor BSVibe-Auth bsvibe-python"

# ─── Usage ───────────────────────────────────────────────────────────
usage() {
  echo "Usage: $(basename "$0") <project> <branch> [slot]"
  echo ""
  echo "Projects: ${ALL_PROJECTS}"
  echo ""
  echo "Slot: 1-${MAX_SLOTS} (auto-assigned if omitted)"
  exit 1
}

# ─── Args ────────────────────────────────────────────────────────────
PROJECT="${1:-}"
BRANCH="${2:-}"
SLOT="${3:-}"

[ -z "$PROJECT" ] || [ -z "$BRANCH" ] && usage

if ! get_base_ports "$PROJECT" >/dev/null 2>&1; then
  echo "Error: Unknown project '$PROJECT'"
  usage
fi

BARE_DIR="${WORKS_DIR}/${PROJECT}/.bare"
WT_DIR="${WORKS_DIR}/${PROJECT}/wt"

[ ! -d "$BARE_DIR" ] && echo "Error: Bare repo not found at $BARE_DIR" && exit 1

# ─── Auto-assign slot ────────────────────────────────────────────────
if [ -z "$SLOT" ]; then
  mkdir -p "$WT_DIR"
  for i in $(seq 1 $MAX_SLOTS); do
    taken=false
    for slotfile in "$BARE_DIR"/worktrees/*/wt-slot; do
      [ ! -f "$slotfile" ] 2>/dev/null && continue
      if [ "$(cat "$slotfile")" = "$i" ]; then
        taken=true
        break
      fi
    done
    if [ "$taken" = false ]; then
      SLOT=$i
      break
    fi
  done
  [ -z "$SLOT" ] && echo "Error: All ${MAX_SLOTS} slots occupied. Remove a worktree first." && exit 1
fi

if [ "$SLOT" -lt 1 ] 2>/dev/null || [ "$SLOT" -gt "$MAX_SLOTS" ] 2>/dev/null; then
  echo "Error: Slot must be 1-${MAX_SLOTS}"
  exit 1
fi

# ─── Parse base ports ────────────────────────────────────────────────
PORTS=($(get_base_ports "$PROJECT"))
BASE_APP="${PORTS[0]}"
BASE_FRONTEND="${PORTS[1]}"
BASE_PG="${PORTS[2]}"
BASE_REDIS="${PORTS[3]}"
EXTRAS=("${PORTS[@]:4}")

# ─── Calculate worktree ports ────────────────────────────────────────
calc_port() {
  local base=$1
  [ "$base" = "-" ] && echo "-" && return
  echo $(( base + OFFSET + SLOT - 1 ))
}

WT_APP=$(calc_port "$BASE_APP")
WT_FRONTEND=$(calc_port "$BASE_FRONTEND")
WT_PG=$(calc_port "$BASE_PG")
WT_REDIS=$(calc_port "$BASE_REDIS")

# ─── Worktree name (sanitize branch) ────────────────────────────────
WT_NAME=$(echo "$BRANCH" | sed 's|/|-|g; s|[^a-zA-Z0-9._-]|-|g')
WT_PATH="${WT_DIR}/${WT_NAME}"

if [ -d "$WT_PATH" ]; then
  echo "Error: Worktree already exists at $WT_PATH"
  exit 1
fi

# ─── Create worktree ────────────────────────────────────────────────
mkdir -p "$WT_DIR"
echo "Creating worktree: ${PROJECT}/wt/${WT_NAME} (branch: ${BRANCH}, slot: ${SLOT})"

cd "$BARE_DIR"
if git show-ref --verify --quiet "refs/heads/${BRANCH}" 2>/dev/null; then
  git worktree add "$WT_PATH" "$BRANCH"
else
  git worktree add "$WT_PATH" -b "$BRANCH"
fi

# ─── Save slot marker (inside git dir, not working tree) ────────────
echo "$SLOT" > "${BARE_DIR}/worktrees/${WT_NAME}/wt-slot"

# ─── Generate .devcontainer/.env ─────────────────────────────────────
DEVCONTAINER_DIR="${WT_PATH}/.devcontainer"
if [ -d "$DEVCONTAINER_DIR" ]; then
  ENV_FILE="${DEVCONTAINER_DIR}/.env"

  {
    echo "# Auto-generated by create-worktree.sh (slot ${SLOT})"
    echo "# Project: ${PROJECT}, Branch: ${BRANCH}"
    echo ""
    [ "$WT_APP" != "-" ]      && echo "EXTERNAL_BACKEND_PORT=${WT_APP}"
    [ "$WT_FRONTEND" != "-" ] && echo "EXTERNAL_FRONTEND_PORT=${WT_FRONTEND}"
    [ "$WT_PG" != "-" ]       && echo "EXTERNAL_PG_PORT=${WT_PG}"
    [ "$WT_REDIS" != "-" ]    && echo "EXTERNAL_REDIS_PORT=${WT_REDIS}"

    # Handle extra ports (e.g., KEYCLOAK=8080)
    for e in "${EXTRAS[@]}"; do
      [ -z "$e" ] && continue
      NAME="${e%%=*}"
      PORT="${e#*=}"
      echo "EXTERNAL_${NAME}_PORT=$(( PORT + OFFSET + SLOT - 1 ))"
    done

  } > "$ENV_FILE"

  echo "  Created: ${ENV_FILE}"

  # ─── Generate docker-compose.override.yml for git worktree ─────────
  BARE_ABS=$(cd "$BARE_DIR" && pwd)
  cat > "${DEVCONTAINER_DIR}/docker-compose.override.yml" <<DCEOF
# Auto-generated by create-worktree.sh
# Mounts .bare at host absolute path so git works inside devcontainer
services:
  app:
    volumes:
      - ${BARE_ABS}:${BARE_ABS}:cached
DCEOF
  echo "  Created: ${DEVCONTAINER_DIR}/docker-compose.override.yml"
fi

# ─── Copy .env from main worktree ──────────────────────────────────
MAIN_WT="${WORKS_DIR}/${PROJECT}/main"
if [ -f "$MAIN_WT/.env" ]; then
  cp "$MAIN_WT/.env" "$WT_PATH/.env"
  echo "  Copied:  ${MAIN_WT}/.env → ${WT_PATH}/.env"
fi

# ─── Summary ─────────────────────────────────────────────────────────
echo ""
echo "╭──────────────────────────────────────────╮"
echo "│  Worktree created successfully           │"
echo "╰──────────────────────────────────────────╯"
echo ""
echo "  Path:   ${WT_PATH}"
echo "  Branch: ${BRANCH}"
echo "  Slot:   ${SLOT}"
echo ""
echo "  Ports:"
[ "$WT_APP" != "-" ]      && echo "    APP:      ${WT_APP}"
[ "$WT_FRONTEND" != "-" ] && echo "    FRONTEND: ${WT_FRONTEND}"
[ "$WT_PG" != "-" ]       && echo "    PG:       ${WT_PG}"
[ "$WT_REDIS" != "-" ]    && echo "    REDIS:    ${WT_REDIS}"
for e in "${EXTRAS[@]}"; do
  [ -z "$e" ] && continue
  NAME="${e%%=*}"
  PORT="${e#*=}"
  printf "    %-10s%s\n" "${NAME}:" "$(( PORT + OFFSET + SLOT - 1 ))"
done
echo ""
echo "  cd ${WT_PATH}"
