#!/usr/bin/env bash
#
# demo-up-local.sh — boot a product's demo stack locally for e2e testing.
#
# Each product's demo backend + DB run in Docker on localhost ports
# offset by +20000 from the prod demo ports (so prod demo containers
# can keep running on the +500 ports). Frontend runs separately via
# `pnpm dev` against the local API.
#
# Usage:
#   demo-up-local.sh <product>           # bring up + print test cmd
#   demo-up-local.sh <product> down      # tear down
#
# Where <product> = BSGateway | BSNexus | BSupervisor | BSage.
#
# The script generates ephemeral DEMO_JWT_SECRET / POSTGRES_PASSWORD
# / REDIS_PASSWORD / ENCRYPTION_KEY each run so test isolation is
# guaranteed (no leftover state).

set -uo pipefail

PRODUCT="${1:-}"
ACTION="${2:-up}"

if [ -z "$PRODUCT" ]; then
  cat <<EOF
Usage: $(basename "$0") <product> [up|down]

Products: BSGateway BSNexus BSupervisor BSage

Up:
  $0 BSGateway

Then in another terminal, drive the e2e tests:
  cd ~/Works/BSGateway/main/frontend
  DEMO_E2E_BASE_URL=http://localhost:14500 \\
  DEMO_E2E_API_URL=http://localhost:14500 \\
    pnpm test:e2e --grep @demo

Down:
  $0 BSGateway down
EOF
  exit 1
fi

# ─── Per-product config ─────────────────────────────────────────────
# Local demo ports = prod demo port + 10000 (so the running prod demo
# containers on Mac Mini don't collide).
case "$PRODUCT" in
  BSGateway)
    APP_PORT=14500       # prod demo: 4500
    PG_PORT=15933        # prod demo: 5933
    REDIS_PORT=16880     # prod demo: 6880
    HEALTH_PATH=/health
    ;;
  BSNexus)
    APP_PORT=18600       # prod demo: 8600
    PG_PORT=15934        # prod demo: 5934
    REDIS_PORT=16881     # prod demo: 6881
    HEALTH_PATH=/health
    ;;
  BSupervisor)
    APP_PORT=19000       # prod demo: 9000
    PG_PORT=15937        # prod demo: 5937
    REDIS_PORT=
    HEALTH_PATH=/api/health
    ;;
  BSage)
    APP_PORT=18900       # prod demo: 8900
    PG_PORT=
    REDIS_PORT=
    HEALTH_PATH=/api/health
    ;;
  *)
    echo "Unknown product: $PRODUCT" >&2
    exit 1
    ;;
esac

PROJECT_ROOT=~/Works/$PRODUCT/main
COMPOSE_FILE="$PROJECT_ROOT/deploy/docker-compose.demo.yml"
ENV_FILE="$PROJECT_ROOT/deploy/.env.demo.local"
COMPOSE_PROJECT="$(echo "$PRODUCT" | tr '[:upper:]' '[:lower:]')-demo-local"

if [ ! -f "$COMPOSE_FILE" ]; then
  echo "No demo compose at $COMPOSE_FILE — has $PRODUCT shipped its demo stack?" >&2
  exit 1
fi

# ─── Down ───────────────────────────────────────────────────────────
if [ "$ACTION" = "down" ]; then
  echo "Tearing down $COMPOSE_PROJECT..."
  docker compose -p "$COMPOSE_PROJECT" -f "$COMPOSE_FILE" down -v
  rm -f "$ENV_FILE"
  exit 0
fi

# ─── Generate ephemeral secrets ─────────────────────────────────────
DEMO_JWT_SECRET=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 16)
REDIS_PASSWORD=$(openssl rand -hex 16)
ENCRYPTION_KEY=$(openssl rand -hex 32)
LITELLM_MASTER_KEY=$(openssl rand -hex 32)

cat > "$ENV_FILE" <<EOF
# Auto-generated by demo-up-local.sh — DO NOT COMMIT.
DEMO_JWT_SECRET=$DEMO_JWT_SECRET
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
ENCRYPTION_KEY=$ENCRYPTION_KEY
LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY
LOG_LEVEL=INFO
EOF
chmod 600 "$ENV_FILE"

# ─── Override compose ports to the local +10000 offsets ──────────────
# Generated alongside the env file so local + prod containers can coexist.
OVERRIDE_FILE="$PROJECT_ROOT/deploy/docker-compose.demo.local.yml"
{
  echo "# Auto-generated by demo-up-local.sh — DO NOT COMMIT."
  echo "services:"
  echo "  app:"
  echo "    container_name: ${COMPOSE_PROJECT}-app"
  echo "    ports:"
  echo "      - \"127.0.0.1:${APP_PORT}:8000\""
  if [ -n "${PG_PORT:-}" ]; then
    echo "  postgres:"
    echo "    container_name: ${COMPOSE_PROJECT}-postgres"
    echo "    ports:"
    echo "      - \"127.0.0.1:${PG_PORT}:5432\""
  fi
  if [ -n "${REDIS_PORT:-}" ]; then
    echo "  redis:"
    echo "    container_name: ${COMPOSE_PROJECT}-redis"
    echo "    ports:"
    echo "      - \"127.0.0.1:${REDIS_PORT}:6379\""
  fi
} > "$OVERRIDE_FILE"

# ─── Bring up ───────────────────────────────────────────────────────
echo "Booting $COMPOSE_PROJECT (DEMO_JWT_SECRET=${DEMO_JWT_SECRET:0:8}...)"
docker compose -p "$COMPOSE_PROJECT" \
  -f "$COMPOSE_FILE" \
  -f "$OVERRIDE_FILE" \
  --env-file "$ENV_FILE" \
  up -d --build

# ─── Run alembic for products that ship migrations ───────────────────
case "$PRODUCT" in
  BSupervisor)
    echo "Running alembic upgrade head…"
    docker compose -p "$COMPOSE_PROJECT" \
      -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" \
      run --rm app python -m alembic upgrade head 2>&1 | tail -5
    docker compose -p "$COMPOSE_PROJECT" \
      -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" \
      restart app
    ;;
esac

# ─── Wait for health ────────────────────────────────────────────────
HEALTH_URL="http://localhost:${APP_PORT}${HEALTH_PATH}"
echo "Waiting for $HEALTH_URL…"
for _ in $(seq 1 60); do
  if curl -fsS -o /dev/null --max-time 2 "$HEALTH_URL" 2>/dev/null; then
    echo "  ✓ healthy"
    break
  fi
  sleep 2
done

# ─── Cheat sheet ────────────────────────────────────────────────────
cat <<EOF

═══════════════════════════════════════════════════════════════
  $PRODUCT demo stack (local) is up.
═══════════════════════════════════════════════════════════════
  Backend:  http://localhost:${APP_PORT}
  Health:   $HEALTH_URL

Run e2e against this stack:
  cd $PROJECT_ROOT/frontend
  DEMO_E2E_BASE_URL=http://localhost:${APP_PORT} \\
  DEMO_E2E_API_URL=http://localhost:${APP_PORT} \\
    pnpm test:e2e --grep @demo

Tear down (incl. volumes):
  $0 $PRODUCT down

Logs:
  docker logs ${COMPOSE_PROJECT}-app --tail=50 -f
EOF
