#!/usr/bin/env bash
set -eo pipefail

# setup-worktree-devcontainer.sh — Fix git in devcontainers for bare repo + worktree projects
#
# Mounts .bare into devcontainers at the same host absolute path so that
# the existing absolute gitdir references in .git files work inside containers.
#
# What it does for each worktree with a .devcontainer/:
#   1. Patches devcontainer.json to use dockerComposeFile array (includes override)
#   2. Adds docker-compose.override.yml to .gitignore (if missing)
#   3. Generates .devcontainer/docker-compose.override.yml with .bare volume mount
#
# Usage:
#   setup-worktree-devcontainer.sh              # all projects
#   setup-worktree-devcontainer.sh bloasis      # single project
#   setup-worktree-devcontainer.sh bloasis bsai # multiple projects

WORKS_DIR=~/Works
ALL_PROJECTS="bloasis BSGateway BSNexus bsai BSForge BSage MetaSummarizer"

# ─── Parse args ────────────────────────────────────────────────────────
if [ $# -gt 0 ]; then
  PROJECTS="$*"
else
  PROJECTS="$ALL_PROJECTS"
fi

# ─── Generate docker-compose.override.yml ──────────────────────────────
generate_override() {
  local bare_dir="$1"
  local devcontainer_dir="$2"

  # Resolve to absolute path
  bare_dir=$(cd "$bare_dir" && pwd)

  cat > "${devcontainer_dir}/docker-compose.override.yml" <<EOF
# Auto-generated by setup-worktree-devcontainer.sh
# Mounts .bare at host absolute path so git works inside devcontainer
services:
  app:
    volumes:
      - ${bare_dir}:${bare_dir}:cached
EOF
}

# ─── Patch devcontainer.json dockerComposeFile ─────────────────────────
patch_devcontainer_json() {
  local dc_json="$1"

  # Skip if already an array
  if grep -q '"dockerComposeFile".*\[' "$dc_json" 2>/dev/null; then
    return 0
  fi

  # Replace string form with array form
  sed -i '' 's|"dockerComposeFile": "docker-compose.yml"|"dockerComposeFile": ["docker-compose.yml", "docker-compose.override.yml"]|' "$dc_json"
}

# ─── Add to .gitignore ────────────────────────────────────────────────
ensure_gitignore() {
  local worktree_dir="$1"
  local gitignore="${worktree_dir}/.gitignore"

  [ ! -f "$gitignore" ] && return 0

  if ! grep -q "docker-compose.override.yml" "$gitignore" 2>/dev/null; then
    # Add under existing docker/devcontainer section or at end
    echo "" >> "$gitignore"
    echo "# Devcontainer local overrides (git worktree mount)" >> "$gitignore"
    echo "docker-compose.override.yml" >> "$gitignore"
  fi
}

# ─── Process one worktree ─────────────────────────────────────────────
process_worktree() {
  local wt_path="$1"
  local bare_dir="$2"
  local devcontainer_dir="${wt_path}/.devcontainer"

  [ ! -d "$devcontainer_dir" ] && return 0

  local dc_json="${devcontainer_dir}/devcontainer.json"
  [ ! -f "$dc_json" ] && return 0

  local wt_name
  wt_name=$(basename "$wt_path")

  # 1. Patch devcontainer.json
  patch_devcontainer_json "$dc_json"

  # 2. Ensure .gitignore has override entry
  ensure_gitignore "$wt_path"

  # 3. Generate override file
  generate_override "$bare_dir" "$devcontainer_dir"

  echo "  [OK] $(basename "$(dirname "$wt_path")")/${wt_name}"
}

# ─── Main ──────────────────────────────────────────────────────────────
echo "Setting up devcontainer git worktree mounts"
echo "============================================"
echo ""

for PROJECT in $PROJECTS; do
  PROJECT_DIR="${WORKS_DIR}/${PROJECT}"
  BARE_DIR="${PROJECT_DIR}/.bare"

  if [ ! -d "$BARE_DIR" ]; then
    echo "  [SKIP] ${PROJECT}: no .bare directory"
    continue
  fi

  echo "${PROJECT}:"

  # Process main/ worktree
  if [ -d "${PROJECT_DIR}/main" ]; then
    process_worktree "${PROJECT_DIR}/main" "$BARE_DIR"
  fi

  # Process wt/* worktrees
  if [ -d "${PROJECT_DIR}/wt" ]; then
    for wt in "${PROJECT_DIR}/wt"/*/; do
      [ -d "$wt" ] || continue
      process_worktree "${wt%/}" "$BARE_DIR"
    done
  fi

  echo ""
done

echo "============================================"
echo "[DONE] Rebuild devcontainers to apply changes"
echo ""
